version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8081:8081"
    volumes:
      - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    links:
      - "wordpress"
    volumes_from:
      - "wordpress:ro"
    environment:
      NGINX_PORT: "8080"

  wordpress-db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: '${WORDPRESS_MYSQL_USER}'
      MYSQL_PASSWORD: '${WORDPRESS_MYSQL_PASSWORD}'

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    image: ellakcy/wordpressswithplugins:alpine-fpm
    links:
      - wordpress-db
    environment:
        WORDPRESS_DB_HOST: wordpress-db:/var/run/mysqld/mysqld.sock
        WORDPRESS_DB_USER: '${WORDPRESS_MYSQL_USER}'
        WORDPRESS_DB_PASSWORD: '${WORDPRESS_MYSQL_PASSWORD}'
        WORDPRESS_ADMIN_USERNAME: '${WORDPRESS_ADMIN_USER}'
        WORDPRESS_ADMIN_PASSWORD: '${WORDPRESS_ADMIN_PASSWORD}'
        WORDPRESS_URL: '${WORDPRESS_URL}'

# Apache Build

  wordpress-apache-db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: '${WORDPRESS_MYSQL_USER}'
      MYSQL_PASSWORD: '${WORDPRESS_MYSQL_PASSWORD}'

  wordpress_apache:
    build:
      context: .
      dockerfile: Dockerfile_apache
    image: ellakcy/wordpressswithplugins:apache
    links:
      - wordpress-apache-db
    ports:
      - "80:8082"
    environment:
        WORDPRESS_DB_HOST: wordpress-apache-db:/var/run/mysqld/mysqld.sock
        WORDPRESS_DB_USER: '${WORDPRESS_MYSQL_USER}'
        WORDPRESS_DB_PASSWORD: '${WORDPRESS_MYSQL_PASSWORD}'
        WORDPRESS_ADMIN_USERNAME: '${WORDPRESS_ADMIN_USER}'
        WORDPRESS_ADMIN_PASSWORD: '${WORDPRESS_ADMIN_PASSWORD}'
        WORDPRESS_URL: '${WORDPRESS_APACHE_URL}'
